# Generated by Django 2.2.2 on 2020-07-09 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quetans',
            name='id',
        ),
        migrations.AddField(
            model_name='quetans',
            name='Q_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
