# Generated by Django 2.2.2 on 2020-07-09 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200709_0012'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quetions',
            fields=[
                ('Q_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('Q_text', models.CharField(max_length=100, unique=True)),
                ('Q_img', models.ImageField(upload_to='')),
                ('Q_tag', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='QuetAns',
        ),
    ]
